spring:
    #数据库配置
    datasource:
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        url: jdbc:p6spy:mysql://localhost:3306/sp_panorama?serverTimezone=Asia/Shanghai
        username: root
        password: root

