kind: pipeline
type: docker
name: default

steps:
  - name: restore cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules
        - ./.pnpm-store
  - name: install dependencies and build
    image: node:21
    commands:
      - cd admin-vue
      - npm i --no-frozen-lockfile
      - npm run build
      - cp -r ./dist /www/wwwroot/panorama/back
trigger:
  ref:
    - refs/heads/master
